name: Build and Deploy

on:
  push:
    branches:
      - develop
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js with PNPM
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build App
        run: npm run build

      - name: Upload Web Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-app
          path: ./dist/apps/web

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist/apps/web/frontend
