name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js with PNPM
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build App
        run: npm run build

      - name: Upload Web Artifact
        uses: actions/upload-artifact@v4
        with:
          name: multi-monitor-web
          path: ./dist/apps/web

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: multi-monitor-web-gh-pages
          path: ./dist/apps/web/frontend
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/apps/web/frontend
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: v1.0.0-${{ github.run_number }}
          files: ./dist/apps/web/*


